/* Copyright (C) 2026 ska_987 — octobre 2026. SPDX-License-Identifier: GPL-3.0-only */
package fr.ska.mesheures;
import android.provider.DocumentsContract;import android.database.Cursor;import org.json.JSONObject;import java.util.concurrent.*;import java.util.zip.*;import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.webkit.*;import android.view.*;import android.print.*;import android.util.Base64;import java.io.*;import java.util.*;
public class MainActivity extends Activity {
 private boolean testAfterPermission;private BackupFiles backups;private final ExecutorService backupWorker=Executors.newSingleThreadExecutor();private ZipOutputStream archive;private File archiveFile;private int archiveSize;private WebView web;private ValueCallback<Uri[]> chooser;private byte[] pending;private static final int EXPORT=10,IMPORT=11,BACKUP_FOLDER=12,RESTORE_BACKUP=13;
 public void onCreate(Bundle b){super.onCreate(b);ReminderReceiver.all(this);backups=new BackupFiles(new File(getFilesDir(),"sauvegardes"));web=new WebView(this);android.widget.FrameLayout root=new android.widget.FrameLayout(this);root.setBackgroundColor(0xfff4f3ee);root.addView(web,new android.widget.FrameLayout.LayoutParams(-1,-1));setContentView(root);getWindow().setStatusBarColor(0xff23594c);getWindow().setNavigationBarColor(0xfff4f3ee);
 if(Build.VERSION.SDK_INT>=30){getWindow().setDecorFitsSystemWindows(false);root.setOnApplyWindowInsetsListener((v,i)->{android.graphics.Insets bars=i.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());android.graphics.Insets keyboard=i.getInsets(WindowInsets.Type.ime());v.setPadding(bars.left,bars.top,bars.right,Math.max(bars.bottom,keyboard.bottom));return WindowInsets.CONSUMED;});root.requestApplyInsets();}
 WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.addJavascriptInterface(new Bridge(),"Android");
 web.setWebViewClient(new WebViewClient(){public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest req){Uri u=req.getUrl();if("app.local".equals(u.getHost())&&"https".equals(u.getScheme())){try{String p=u.getPath();if(p==null||p.equals("/"))p="/index.html";if(p.contains(".."))throw new IOException();String name=p.substring(1);String mime=name.endsWith(".html")?"text/html":name.endsWith(".js")?"application/javascript":name.endsWith(".css")?"text/css":name.endsWith(".svg")?"image/svg+xml":name.endsWith(".zip")?"application/zip":name.endsWith(".json")?"application/json":"text/plain";return new WebResourceResponse(mime,"UTF-8",getAssets().open(name));}catch(IOException e){return new WebResourceResponse("text/plain","UTF-8",404,"Not Found",new HashMap<>(),new ByteArrayInputStream(new byte[0]));}}return new WebResourceResponse("text/plain","UTF-8",403,"Forbidden",new HashMap<>(),new ByteArrayInputStream(new byte[0]));}
 public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();if("mailto".equals(u.getScheme())){try{startActivity(new Intent(Intent.ACTION_SENDTO,u));}catch(ActivityNotFoundException e){new AlertDialog.Builder(MainActivity.this).setMessage("Aucune messagerie installée. Contact : sav.centreprotech@proton.me").setPositiveButton("OK",null).show();}return true;}if("https".equals(u.getScheme())&&"app.local".equals(u.getHost())){if(u.getPath().endsWith("hora-ohipa-source.zip")){exportSource();return true;}return false;}return true;}});
 web.setWebChromeClient(new WebChromeClient(){public boolean onJsAlert(WebView v,String u,String msg,JsResult r){new AlertDialog.Builder(MainActivity.this).setMessage(msg).setPositiveButton("OK",(d,w)->r.confirm()).setOnCancelListener(d->r.cancel()).show();return true;}public boolean onJsConfirm(WebView v,String u,String msg,JsResult r){new AlertDialog.Builder(MainActivity.this).setMessage(msg).setPositiveButton("Oui",(d,w)->r.confirm()).setNegativeButton("Annuler",(d,w)->r.cancel()).setOnCancelListener(d->r.cancel()).show();return true;}public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> c,FileChooserParams p){if(chooser!=null)chooser.onReceiveValue(null);chooser=c;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMPORT);return true;}});web.loadUrl("https://app.local/index.html");}
 private void fail(Exception e){new AlertDialog.Builder(this).setMessage("Impossible de terminer cette action. Réessayez ou exportez vos données.").setPositiveButton("OK",null).show();}
 private void exportSource(){try(InputStream i=getAssets().open("hora-ohipa-source.zip")){ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] buf=new byte[8192];int n;while((n=i.read(buf))!=-1)o.write(buf,0,n);export(o.toByteArray(),"Hora-Ohipa-source-beta1.15.zip","application/zip");}catch(Exception e){fail(e);}}
 private void export(byte[] bytes,String name,String mime){pending=bytes;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime);i.putExtra(Intent.EXTRA_TITLE,name);startActivityForResult(i,EXPORT);}
 private void share(byte[] bytes,String name,String mime){try{File f=new File(getCacheDir(),name);try(FileOutputStream o=new FileOutputStream(f)){o.write(bytes);}Uri u=Uri.parse("content://fr.ska.mesheures.files/"+name);Intent i=new Intent(Intent.ACTION_SEND);i.setType(mime);i.putExtra(Intent.EXTRA_STREAM,u);i.putExtra(Intent.EXTRA_SUBJECT,"Votre facture "+name);i.setClipData(ClipData.newRawUri(name,u));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Envoyer la facture"));}catch(Exception e){fail(e);}}
 private void print(byte[] bytes,String name){PrintManager pm=(PrintManager)getSystemService(PRINT_SERVICE);pm.print(name,new PrintDocumentAdapter(){public void onLayout(PrintAttributes a,PrintAttributes b,CancellationSignal c,LayoutResultCallback cb,Bundle extras){if(c.isCanceled()){cb.onLayoutCancelled();return;}cb.onLayoutFinished(new PrintDocumentInfo.Builder(name).setContentType(PrintDocumentInfo.CONTENT_TYPE_DOCUMENT).setPageCount(PrintDocumentInfo.PAGE_COUNT_UNKNOWN).build(),true);}public void onWrite(PageRange[] pages,ParcelFileDescriptor fd,CancellationSignal c,WriteResultCallback cb){if(c.isCanceled()){cb.onWriteCancelled();return;}try(FileOutputStream o=new FileOutputStream(fd.getFileDescriptor())){o.write(bytes);cb.onWriteFinished(new PageRange[]{PageRange.ALL_PAGES});}catch(Exception e){cb.onWriteFailed("Échec de l’impression");}}},null);}
 private void backupResult(boolean local,boolean folder){runOnUiThread(()->web.evaluateJavascript("backupSaved("+local+","+folder+")",null));}
 private void copyToFolder(byte[] data)throws Exception{String saved=getPreferences(0).getString("backupFolder","");if(saved.isEmpty())return;Uri tree=Uri.parse(saved),parent=DocumentsContract.buildDocumentUriUsingTree(tree,DocumentsContract.getTreeDocumentId(tree));Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(tree,DocumentsContract.getTreeDocumentId(tree));Uri target=null;
  try(Cursor c=getContentResolver().query(children,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME},null,null,null)){if(c!=null)while(c.moveToNext())if("Hora-Ohipa-donnees.json".equals(c.getString(1))){target=DocumentsContract.buildDocumentUriUsingTree(tree,c.getString(0));break;}}
  if(target==null)target=DocumentsContract.createDocument(getContentResolver(),parent,"application/json","Hora-Ohipa-donnees.json");if(target==null)throw new IOException();try(OutputStream out=getContentResolver().openOutputStream(target,"rwt")){if(out==null)throw new IOException();out.write(data);}
 }
 private void queueBackup(String json){backupWorker.execute(()->{boolean local=false,folder=false;try{byte[] bytes=json.getBytes("UTF-8");backups.save(bytes);local=true;copyToFolder(bytes);folder=true;}catch(Exception e){}backupResult(local,folder);});}
 private void restoreText(String data){runOnUiThread(()->web.evaluateJavascript("restoreBackupText("+JSONObject.quote(data)+")",null));}
 private void restorePicked(Uri uri){backupWorker.execute(()->{try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IOException();PushbackInputStream stream=new PushbackInputStream(in,4);byte[] head=new byte[4];int n=stream.read(head);if(n>0)stream.unread(head,0,n);if(n>=2&&head[0]=='P'&&head[1]=='K'){ZipInputStream zip=new ZipInputStream(stream);ZipEntry e;while((e=zip.getNextEntry())!=null){if("donnees.json".equals(e.getName())){restoreText(new String(BackupFiles.read(zip,20000000),"UTF-8"));return;}}throw new IOException();}restoreText(new String(BackupFiles.read(stream,20000000),"UTF-8"));}catch(Exception e){runOnUiThread(()->fail(e));}});}
 private void shareArchive(File f){Uri uri=Uri.parse("content://fr.ska.mesheures.files/"+f.getName());Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/zip");i.putExtra(Intent.EXTRA_STREAM,uri);i.putExtra(Intent.EXTRA_SUBJECT,"Sauvegarde Hora ‘ohipa");i.setClipData(ClipData.newRawUri(f.getName(),uri));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);try{startActivity(Intent.createChooser(i,"Choisir Drive pour sauvegarder"));}catch(Exception e){fail(e);}}
 public class Bridge {
 @JavascriptInterface public void syncReminders(String json,boolean running){ReminderReceiver.sync(MainActivity.this,json,running);}
 @JavascriptInterface public boolean notificationsAllowed(){NotificationManager n=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);ReminderReceiver.channel(MainActivity.this);return n.areNotificationsEnabled()&&n.getNotificationChannel(ReminderReceiver.CHANNEL).getImportance()!=NotificationManager.IMPORTANCE_NONE;}
 @JavascriptInterface public void notificationPermission(boolean test){runOnUiThread(()->{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=android.content.pm.PackageManager.PERMISSION_GRANTED){testAfterPermission=test;requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},70);}else if(test)ReminderReceiver.notify(MainActivity.this,0,true);});}
 @JavascriptInterface public void notificationSettings(){runOnUiThread(()->{Intent i=new Intent(android.provider.Settings.ACTION_CHANNEL_NOTIFICATION_SETTINGS);i.putExtra(android.provider.Settings.EXTRA_APP_PACKAGE,getPackageName());i.putExtra(android.provider.Settings.EXTRA_CHANNEL_ID,ReminderReceiver.CHANNEL);startActivity(i);});}

 @JavascriptInterface public String latestBackup(){return backups.latest();}
 @JavascriptInterface public String backupFolder(){return getPreferences(0).getString("backupFolder","");}
 @JavascriptInterface public void backupData(String json){if(json.length()<=20000000)queueBackup(json);}
 @JavascriptInterface public void chooseBackupFolder(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,BACKUP_FOLDER);});}
 @JavascriptInterface public void restoreFile(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,RESTORE_BACKUP);});}
 @JavascriptInterface public void restoreLocal(){runOnUiThread(()->{File[] files=backups.list();if(files.length==0){new AlertDialog.Builder(MainActivity.this).setMessage("Aucune copie locale disponible.").setPositiveButton("OK",null).show();return;}String[] labels=new String[files.length];java.text.DateFormat fmt=java.text.DateFormat.getDateTimeInstance(java.text.DateFormat.SHORT,java.text.DateFormat.MEDIUM);for(int n=0;n<files.length;n++)labels[n]=fmt.format(new Date(files[n].lastModified()));new AlertDialog.Builder(MainActivity.this).setTitle("Choisir une copie locale").setItems(labels,(d,w)->backupWorker.execute(()->{try(FileInputStream in=new FileInputStream(files[w])){restoreText(new String(BackupFiles.read(in,20000000),"UTF-8"));}catch(Exception e){runOnUiThread(()->fail(e));}})).setNegativeButton("Annuler",null).show();});}
 @JavascriptInterface public synchronized boolean archiveBegin(String json){if(json.length()>20000000)return false;try{if(archive!=null)archive.close();archiveFile=new File(getCacheDir(),"Hora-Ohipa-sauvegarde-"+System.currentTimeMillis()+".zip");archive=new ZipOutputStream(new FileOutputStream(archiveFile));byte[] bytes=json.getBytes("UTF-8");archiveSize=bytes.length;archive.putNextEntry(new ZipEntry("donnees.json"));archive.write(bytes);archive.closeEntry();return true;}catch(Exception e){archiveAbort();return false;}}
 @JavascriptInterface public synchronized boolean archivePdf(String name,String encoded){try{if(archive==null||encoded.length()>30000000)return false;byte[] bytes=Base64.decode(encoded,Base64.DEFAULT);archiveSize+=bytes.length;if(archiveSize>100000000)throw new IOException();archive.putNextEntry(new ZipEntry("factures/"+name.replaceAll("[^A-Za-z0-9._-]","_")));archive.write(bytes);archive.closeEntry();return true;}catch(Exception e){archiveAbort();return false;}}
 @JavascriptInterface public synchronized boolean archiveFinish(){try{if(archive==null)return false;archive.close();archive=null;File ready=archiveFile;archiveFile=null;runOnUiThread(()->shareArchive(ready));return true;}catch(Exception e){archiveAbort();return false;}}
 @JavascriptInterface public synchronized void archiveAbort(){try{if(archive!=null)archive.close();}catch(Exception e){}archive=null;if(archiveFile!=null)archiveFile.delete();archiveFile=null;}
@JavascriptInterface public void source(){runOnUiThread(()->exportSource());} @JavascriptInterface public void file(String encoded,String name,String mime,String action){if(encoded.length()>30000000)return;byte[] bytes;try{bytes=Base64.decode(encoded,Base64.DEFAULT);}catch(Exception e){return;}String safe=name.replaceAll("[^A-Za-z0-9._-]","_");runOnUiThread(()->{if("share".equals(action))share(bytes,safe,mime);else if("print".equals(action))print(bytes,safe);else export(bytes,safe,mime);});}}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==RESTORE_BACKUP&&result==RESULT_OK&&data!=null)restorePicked(data.getData());if(request==BACKUP_FOLDER&&result==RESULT_OK&&data!=null){try{Uri uri=data.getData();getContentResolver().takePersistableUriPermission(uri,data.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));getPreferences(0).edit().putString("backupFolder",uri.toString()).apply();web.evaluateJavascript("backupFolderChosen()",null);}catch(Exception e){fail(e);}}if(request==IMPORT&&chooser!=null){chooser.onReceiveValue(result==RESULT_OK&&data!=null?new Uri[]{data.getData()}:null);chooser=null;}if(request==EXPORT){if(result==RESULT_OK&&data!=null&&pending!=null){try(OutputStream o=getContentResolver().openOutputStream(data.getData())){o.write(pending);new AlertDialog.Builder(this).setMessage("Fichier enregistré.").setPositiveButton("OK",null).show();}catch(Exception e){fail(e);}}pending=null;}}
 public void onRequestPermissionsResult(int code,String[] permissions,int[] grants){super.onRequestPermissionsResult(code,permissions,grants);if(code==70){if(testAfterPermission&&grants.length>0&&grants[0]==android.content.pm.PackageManager.PERMISSION_GRANTED)ReminderReceiver.notify(this,0,true);testAfterPermission=false;web.evaluateJavascript("updateReminderPermission()",null);}}
 protected void onResume(){super.onResume();if(web!=null)web.evaluateJavascript("if(typeof updateReminderPermission==='function')updateReminderPermission()",null);}
 public void onBackPressed(){web.evaluateJavascript("document.querySelector('dialog[open]') ? (document.querySelector('dialog[open]').close(), true) : false",result->{if(!"true".equals(result)){if(web.canGoBack())web.goBack();else new AlertDialog.Builder(this).setMessage("Fermer Hora ‘ohipa ? Le pointage en cours sera conservé.").setPositiveButton("Fermer",(d,w)->finish()).setNegativeButton("Rester",null).show();}});}
}
