/* Copyright (C) 2026 ska_987. SPDX-License-Identifier: GPL-3.0-only */
package fr.ska.mesheures;
import android.app.*;import android.content.*;import android.os.*;import org.json.*;import java.util.*;
public class ReminderReceiver extends BroadcastReceiver {
 static final String CHANNEL="hora_rappels_v1",ACTION="fr.ska.mesheures.REMINDER";
 static SharedPreferences prefs(Context c){return c.getSharedPreferences("rappels",0);}
 static void channel(Context c){NotificationManager n=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);NotificationChannel ch=new NotificationChannel(CHANNEL,"Rappels de pointage",NotificationManager.IMPORTANCE_HIGH);ch.setDescription("Arrivée et départ aux jours et heures choisis");ch.enableVibration(true);n.createNotificationChannel(ch);}
 static PendingIntent pending(Context c,int kind,long due){Intent i=new Intent(c,ReminderReceiver.class).setAction(ACTION).putExtra("kind",kind).putExtra("due",due);return PendingIntent.getBroadcast(c,kind,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 static void schedule(Context c,int kind){SharedPreferences p=prefs(c);AlarmManager a=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);String key=kind==0?"arrival":"departure";long at=p.getBoolean(key+"On",false)?ReminderTimes.next(System.currentTimeMillis(),p.getString(key+"Time",kind==0?"08:00":"17:00"),p.getInt("days",0),TimeZone.getDefault()):-1;a.cancel(pending(c,kind,at));p.edit().putLong(key+"Due",at).apply();if(at>0)a.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pending(c,kind,at));}
 static void all(Context c){channel(c);schedule(c,0);schedule(c,1);}
 static void sync(Context c,String raw,boolean running){try{JSONObject o=new JSONObject(raw);int days=o.optInt("days",0)&127;String ar=o.optString("arrivalTime","08:00"),de=o.optString("departureTime","17:00");boolean ao=o.optBoolean("arrivalOn",false),d=o.optBoolean("departureOn",false);if(!ar.matches("([01][0-9]|2[0-3]):[0-5][0-9]")||!de.matches("([01][0-9]|2[0-3]):[0-5][0-9]"))return;SharedPreferences p=prefs(c);boolean changed=p.getInt("days",0)!=days||p.getBoolean("arrivalOn",false)!=ao||p.getBoolean("departureOn",false)!=d||!p.getString("arrivalTime","").equals(ar)||!p.getString("departureTime","").equals(de);p.edit().putInt("days",days).putBoolean("arrivalOn",ao).putBoolean("departureOn",d).putString("arrivalTime",ar).putString("departureTime",de).putBoolean("running",running).commit();NotificationManager nm=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);nm.cancel(running?200:201);if(!ao)nm.cancel(200);if(!d)nm.cancel(201);if(changed)all(c);}catch(Exception e){}}
 static void notify(Context c,int kind,boolean test){channel(c);NotificationManager n=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(!n.areNotificationsEnabled())return;Intent open=new Intent(c,MainActivity.class).setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent tap=PendingIntent.getActivity(c,0,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);String title=test?"Test du rappel":kind==0?"Pensez à pointer votre arrivée":"Votre pointage est toujours en cours";String body=test?"Les rappels utilisent ce son et ces réglages.":kind==0?"Touchez pour ouvrir Hora ‘ohipa et démarrer votre pointage.":"Avez-vous terminé ? Touchez pour vérifier et pointer votre départ.";try{n.notify(test?202:200+kind,new Notification.Builder(c,CHANNEL).setSmallIcon(c.getResources().getIdentifier("ic_notification","drawable",c.getPackageName())).setContentTitle(title).setContentText(body).setStyle(new Notification.BigTextStyle().bigText(body)).setContentIntent(tap).setAutoCancel(true).setCategory(Notification.CATEGORY_REMINDER).setVisibility(Notification.VISIBILITY_PRIVATE).build());}catch(SecurityException e){}}
 public void onReceive(Context c,Intent intent){if(!ACTION.equals(intent.getAction())){all(c);return;}int kind=intent.getIntExtra("kind",-1);if(kind<0||kind>1)return;SharedPreferences p=prefs(c);String key=kind==0?"arrival":"departure";long due=intent.getLongExtra("due",0);if(!p.getBoolean(key+"On",false)||due!=p.getLong(key+"Due",-1))return;schedule(c,kind);long delay=System.currentTimeMillis()-due;boolean running=p.getBoolean("running",false);if(!ReminderTimes.shouldNotify(kind,running,delay))return;Calendar date=Calendar.getInstance();date.setTimeInMillis(due);String stamp=date.get(Calendar.YEAR)+"-"+date.get(Calendar.DAY_OF_YEAR);if(stamp.equals(p.getString(key+"Shown","")))return;p.edit().putString(key+"Shown",stamp).apply();notify(c,kind,false);}
}
